-- =====     << Exercício Colaborativo 1 da Aula 3 - Evolução 2 (Oracle)>>     =====
--
--                    SCRIPT DE CRIACAO (DDL)
--
-- Data Criacao ...........: 30/06/2025
-- Autor(es) ..............: Luciano de Freitas Melo, Maria Eduarda dos Santos Abritta Ferreira, Matheus Henrique dos Santos
-- Banco de Dados .........: ORACLE
-- Base de Dados (nome) ...: VRVR
--
-- PROJETO => 01 Base de Dados
--         => 07 Tabelas
--         => 05 Sequencias
--         => 01 View
--         => 02 Índices
-- 
-- 
-- ULTIMAS ATUALIZACOES
-- 08/07/2025 => Adição da Tabela ALA
--            => Adição sequência do ID da ALA 
--
-- ------------------------------------------------------------------------------------------------------


CREATE SEQUENCE GF_SEQ_ID_SETOR
    MINVALUE 1
    MAXVALUE 9999999
    START WITH 1
    INCREMENT BY 1;

CREATE SEQUENCE GF_SEQ_ID_ALA
    MINVALUE 1
    MAXVALUE 9999999
    START WITH 1
    INCREMENT BY 1;

CREATE SEQUENCE GF_SEQ_ID_ESPECIALIDADE
    MINVALUE 1
    MAXVALUE 9999999
    START WITH 1
    INCREMENT BY 1;

CREATE SEQUENCE GF_SEQ_ID_HORARIO
    MINVALUE 1
    MAXVALUE 9999999
    START WITH 1
    INCREMENT BY 1;

CREATE SEQUENCE GF_SEQ_ID_ALOCACAO
    MINVALUE 1
    MAXVALUE 9999999
    START WITH 1
    INCREMENT BY 1;


CREATE TABLE GF_SETOR (
    ID_SETOR NUMBER PRIMARY KEY,
    NOME_SETOR VARCHAR2(100) NOT NULL
);

CREATE TABLE GF_ALA (
    ID_ALA NUMBER PRIMARY KEY,
    ID_SETOR NUMBER NOT NULL,
    NOME_ALA VARCHAR2(100) NOT NULL,
    QTDE_QUARTOS NUMBER NOT NULL CHECK (QTDE_QUARTOS >= 1),
    QTDE_SALAS_CIRURGIA NUMBER DEFAULT 0,
    QTDE_ENFERMARIAS NUMBER NOT NULL CHECK (QTDE_ENFERMARIAS >= 1),
    QTDE_PROFISSIONAIS NUMBER NOT NULL CHECK (QTDE_PROFISSIONAIS >= 1),
    CONSTRAINT GF_ALA_SETOR_FK FOREIGN KEY (ID_SETOR) REFERENCES GF_SETOR(ID_SETOR)
);

CREATE TABLE GF_ESPECIALIDADE (
    ID_ESPECIALIDADE NUMBER PRIMARY KEY,
    NOME_ESPECIALIDADE VARCHAR2(100) NOT NULL
);

CREATE TABLE GF_PLANTONISTA (
    MATRICULA NUMBER PRIMARY KEY,
    NOME_COMPLETO VARCHAR2(250) NOT NULL,
    SEXO VARCHAR2(1) NOT NULL
);

CREATE TABLE GF_HORARIO (
    ID_HORARIO NUMBER PRIMARY KEY,
    HORA_INICIO TIMESTAMP NOT NULL,
    HORA_FIM TIMESTAMP NOT NULL
);

CREATE TABLE GF_ALOCACAO (
    ID_ALOCACAO NUMBER PRIMARY KEY,
    ID_HORARIO NUMBER NOT NULL,
    ID_SETOR NUMBER NOT NULL,
    MATRICULA_PLANTONISTA NUMBER NOT NULL,
    CONSTRAINT GF_ALOCACAO_UK UNIQUE (ID_HORARIO, ID_SETOR, MATRICULA_PLANTONISTA),
    CONSTRAINT GF_ALOCACAO_HORARIO_FK FOREIGN KEY (ID_HORARIO) REFERENCES GF_HORARIO(ID_HORARIO),
    CONSTRAINT GF_ALOCACAO_SETOR_FK FOREIGN KEY (ID_SETOR) REFERENCES GF_SETOR(ID_SETOR),
    CONSTRAINT GF_ALOCACAO_PLANTONISTA_FK FOREIGN KEY (MATRICULA_PLANTONISTA) REFERENCES GF_PLANTONISTA(MATRICULA)
);

CREATE TABLE GF_TEM (
    ID_ESPECIALIDADE NUMBER NOT NULL,
    MATRICULA_PLANTONISTA NUMBER NOT NULL,
    CONSTRAINT GF_TEM_UK UNIQUE (ID_ESPECIALIDADE, MATRICULA_PLANTONISTA),
    CONSTRAINT GF_TEM_ESPECIALIDADE_FK FOREIGN KEY (ID_ESPECIALIDADE) REFERENCES GF_ESPECIALIDADE(ID_ESPECIALIDADE),
    CONSTRAINT GF_TEM_PLANTONISTA_FK FOREIGN KEY (MATRICULA_PLANTONISTA) REFERENCES GF_PLANTONISTA(MATRICULA)
);
