-- =====     << Exercício Colaborativo 1 da Aula 3 - Evolução 2 (Oracle) >>     =====
--
--                    SCRIPT DE POPULA (DML)
--
-- Data Criacao ...........: 30/06/2025
-- Autor(es) ..............: Luciano de Freitas Melo, Maria Eduarda dos Santos Abritta Ferreira, Matheus Henrique dos Santos
-- Banco de Dados .........: ORACLE
-- Base de Dados (nome) ...: VRVR
--
-- PROJETO => 01 Base de Dados
--         => 07 Tabelas
--         => 05 Sequencias
--         => 01 View
--         => 02 Índices
-- 
-- 
-- ULTIMAS ATUALIZACOES
-- 09/07/2025 => chamada dos valores das sequencias para as respectivas tabelas: 
--               SETOR, ALA, ESPECIALIDADE, HORARIO e ALOCACAO
--
-- ---------------------------------------------------------

INSERT INTO GF_SETOR (ID_SETOR, NOME_SETOR) VALUES (GF_SEQ_ID_SETOR.nextval, 'Emergência');
INSERT INTO GF_SETOR (ID_SETOR, NOME_SETOR) VALUES (GF_SEQ_ID_SETOR.nextval, 'UTI Adulto');
INSERT INTO GF_SETOR (ID_SETOR, NOME_SETOR) VALUES (GF_SEQ_ID_SETOR.nextval, 'Centro Cirúrgico');
INSERT INTO GF_SETOR (ID_SETOR, NOME_SETOR) VALUES (GF_SEQ_ID_SETOR.nextval, 'Pediatria');
INSERT INTO GF_SETOR (ID_SETOR, NOME_SETOR) VALUES (GF_SEQ_ID_SETOR.nextval, 'Cardiologia');
INSERT INTO GF_SETOR (ID_SETOR, NOME_SETOR) VALUES (GF_SEQ_ID_SETOR.nextval, 'Neurologia');


INSERT INTO GF_ALA (ID_ALA, ID_SETOR, NOME_ALA, QTDE_QUARTOS, QTDE_SALAS_CIRURGIA, QTDE_ENFERMARIAS, QTDE_PROFISSIONAIS) 
     VALUES (GF_SEQ_ID_ALA.nextval, 1, 'Emergência Ala Norte', 8, 2, 3, 6);
INSERT INTO GF_ALA (ID_ALA, ID_SETOR, NOME_ALA, QTDE_QUARTOS, QTDE_SALAS_CIRURGIA, QTDE_ENFERMARIAS, QTDE_PROFISSIONAIS) 
     VALUES (GF_SEQ_ID_ALA.nextval, 1, 'Emergência Ala Sul', 10, 1, 4, 8);
INSERT INTO GF_ALA (ID_ALA, ID_SETOR, NOME_ALA, QTDE_QUARTOS, QTDE_SALAS_CIRURGIA, QTDE_ENFERMARIAS, QTDE_PROFISSIONAIS) 
     VALUES (GF_SEQ_ID_ALA.nextval, 2, 'UTI Ala Leste', 12, 0, 2, 10);
INSERT INTO GF_ALA (ID_ALA, ID_SETOR, NOME_ALA, QTDE_QUARTOS, QTDE_SALAS_CIRURGIA, QTDE_ENFERMARIAS, QTDE_PROFISSIONAIS) 
     VALUES (GF_SEQ_ID_ALA.nextval, 3, 'Centro Cirúrgico Principal', 6, 8, 1, 12);
INSERT INTO GF_ALA (ID_ALA, ID_SETOR, NOME_ALA, QTDE_QUARTOS, QTDE_SALAS_CIRURGIA, QTDE_ENFERMARIAS, QTDE_PROFISSIONAIS) 
     VALUES (GF_SEQ_ID_ALA.nextval, 4, 'Pediatria Ala Oeste', 15, 0, 5, 7);
INSERT INTO GF_ALA (ID_ALA, ID_SETOR, NOME_ALA, QTDE_QUARTOS, QTDE_SALAS_CIRURGIA, QTDE_ENFERMARIAS, QTDE_PROFISSIONAIS) 
     VALUES (GF_SEQ_ID_ALA.nextval, 5, 'Cardiologia Intensiva', 8, 2, 2, 9);

INSERT INTO GF_ESPECIALIDADE (ID_ESPECIALIDADE, NOME_ESPECIALIDADE) VALUES (GF_SEQ_ID_ESPECIALIDADE.nextval, 'Enfermeiro Geral');
INSERT INTO GF_ESPECIALIDADE (ID_ESPECIALIDADE, NOME_ESPECIALIDADE) VALUES (GF_SEQ_ID_ESPECIALIDADE.nextval, 'Cardiologia');
INSERT INTO GF_ESPECIALIDADE (ID_ESPECIALIDADE, NOME_ESPECIALIDADE) VALUES (GF_SEQ_ID_ESPECIALIDADE.nextval, 'Neurologia');
INSERT INTO GF_ESPECIALIDADE (ID_ESPECIALIDADE, NOME_ESPECIALIDADE) VALUES (GF_SEQ_ID_ESPECIALIDADE.nextval, 'Pediatria');
INSERT INTO GF_ESPECIALIDADE (ID_ESPECIALIDADE, NOME_ESPECIALIDADE) VALUES (GF_SEQ_ID_ESPECIALIDADE.nextval, 'Cirurgia Geral');
INSERT INTO GF_ESPECIALIDADE (ID_ESPECIALIDADE, NOME_ESPECIALIDADE) VALUES (GF_SEQ_ID_ESPECIALIDADE.nextval, 'UTI');
INSERT INTO GF_ESPECIALIDADE (ID_ESPECIALIDADE, NOME_ESPECIALIDADE) VALUES (GF_SEQ_ID_ESPECIALIDADE.nextval, 'Emergência');
INSERT INTO GF_ESPECIALIDADE (ID_ESPECIALIDADE, NOME_ESPECIALIDADE) VALUES (GF_SEQ_ID_ESPECIALIDADE.nextval, 'Oncologia');

INSERT ALL
    INTO GF_PLANTONISTA (MATRICULA, NOME_COMPLETO, SEXO) VALUES (12001, 'Ana Carolina Silva Santos', 'F')
    INTO GF_PLANTONISTA (MATRICULA, NOME_COMPLETO, SEXO) VALUES (12002, 'Carlos Eduardo Oliveira Lima', 'M')
    INTO GF_PLANTONISTA (MATRICULA, NOME_COMPLETO, SEXO) VALUES (12003, 'Maria Fernanda Costa Almeida', 'F')
    INTO GF_PLANTONISTA (MATRICULA, NOME_COMPLETO, SEXO) VALUES (12004, 'Roberto José Ferreira Souza', 'M')
    INTO GF_PLANTONISTA (MATRICULA, NOME_COMPLETO, SEXO) VALUES (12005, 'Juliana Aparecida Rodrigues', 'F')
    INTO GF_PLANTONISTA (MATRICULA, NOME_COMPLETO, SEXO) VALUES (12006, 'Anderson Luiz Barbosa Mendes', 'M')
    INTO GF_PLANTONISTA (MATRICULA, NOME_COMPLETO, SEXO) VALUES (12007, 'Patricia Helena Nascimento', 'F')
    INTO GF_PLANTONISTA (MATRICULA, NOME_COMPLETO, SEXO) VALUES (12008, 'Marcos Antonio Pereira Santos', 'M')
    INTO GF_PLANTONISTA (MATRICULA, NOME_COMPLETO, SEXO) VALUES (12009, 'Fernanda Cristina Moreira', 'F')
    INTO GF_PLANTONISTA (MATRICULA, NOME_COMPLETO, SEXO) VALUES (12010, 'Leonardo Henrique Campos', 'M')
SELECT * FROM DUAL;

INSERT ALL
    INTO GF_TEM (ID_ESPECIALIDADE, MATRICULA_PLANTONISTA) VALUES (1, 12001)
    INTO GF_TEM (ID_ESPECIALIDADE, MATRICULA_PLANTONISTA) VALUES (2, 12002)
    INTO GF_TEM (ID_ESPECIALIDADE, MATRICULA_PLANTONISTA) VALUES (3, 12002)
    INTO GF_TEM (ID_ESPECIALIDADE, MATRICULA_PLANTONISTA) VALUES (4, 12003)
    INTO GF_TEM (ID_ESPECIALIDADE, MATRICULA_PLANTONISTA) VALUES (5, 12004)
    INTO GF_TEM (ID_ESPECIALIDADE, MATRICULA_PLANTONISTA) VALUES (6, 12005)
    INTO GF_TEM (ID_ESPECIALIDADE, MATRICULA_PLANTONISTA) VALUES (7, 12005)
    INTO GF_TEM (ID_ESPECIALIDADE, MATRICULA_PLANTONISTA) VALUES (2, 12006)
    INTO GF_TEM (ID_ESPECIALIDADE, MATRICULA_PLANTONISTA) VALUES (1, 12007)
    INTO GF_TEM (ID_ESPECIALIDADE, MATRICULA_PLANTONISTA) VALUES (6, 12008)
    INTO GF_TEM (ID_ESPECIALIDADE, MATRICULA_PLANTONISTA) VALUES (4, 12009)
    INTO GF_TEM (ID_ESPECIALIDADE, MATRICULA_PLANTONISTA) VALUES (7, 12010)
SELECT * FROM DUAL;

INSERT INTO GF_HORARIO (ID_HORARIO, HORA_INICIO, HORA_FIM) VALUES (GF_SEQ_ID_HORARIO.nextval, TO_TIMESTAMP('2024-12-15 07:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2024-12-15 13:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO GF_HORARIO (ID_HORARIO, HORA_INICIO, HORA_FIM) VALUES (GF_SEQ_ID_HORARIO.nextval, TO_TIMESTAMP('2024-12-15 13:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2024-12-15 19:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO GF_HORARIO (ID_HORARIO, HORA_INICIO, HORA_FIM) VALUES (GF_SEQ_ID_HORARIO.nextval, TO_TIMESTAMP('2024-12-15 19:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2024-12-16 07:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO GF_HORARIO (ID_HORARIO, HORA_INICIO, HORA_FIM) VALUES (GF_SEQ_ID_HORARIO.nextval, TO_TIMESTAMP('2024-12-16 07:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2024-12-16 13:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO GF_HORARIO (ID_HORARIO, HORA_INICIO, HORA_FIM) VALUES (GF_SEQ_ID_HORARIO.nextval, TO_TIMESTAMP('2024-12-16 13:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2024-12-16 19:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO GF_HORARIO (ID_HORARIO, HORA_INICIO, HORA_FIM) VALUES (GF_SEQ_ID_HORARIO.nextval, TO_TIMESTAMP('2024-12-21 08:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2024-12-21 20:00:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO GF_ALOCACAO (ID_ALOCACAO, ID_HORARIO, ID_SETOR, MATRICULA_PLANTONISTA) VALUES (GF_SEQ_ID_ALOCACAO.nextval, 1, 1, 12001);
INSERT INTO GF_ALOCACAO (ID_ALOCACAO, ID_HORARIO, ID_SETOR, MATRICULA_PLANTONISTA) VALUES (GF_SEQ_ID_ALOCACAO.nextval, 1, 1, 12002);
INSERT INTO GF_ALOCACAO (ID_ALOCACAO, ID_HORARIO, ID_SETOR, MATRICULA_PLANTONISTA) VALUES (GF_SEQ_ID_ALOCACAO.nextval, 1, 2, 12003);
INSERT INTO GF_ALOCACAO (ID_ALOCACAO, ID_HORARIO, ID_SETOR, MATRICULA_PLANTONISTA) VALUES (GF_SEQ_ID_ALOCACAO.nextval, 2, 2, 12004);
INSERT INTO GF_ALOCACAO (ID_ALOCACAO, ID_HORARIO, ID_SETOR, MATRICULA_PLANTONISTA) VALUES (GF_SEQ_ID_ALOCACAO.nextval, 2, 2, 12006);
INSERT INTO GF_ALOCACAO (ID_ALOCACAO, ID_HORARIO, ID_SETOR, MATRICULA_PLANTONISTA) VALUES (GF_SEQ_ID_ALOCACAO.nextval, 3, 3, 12005);
INSERT INTO GF_ALOCACAO (ID_ALOCACAO, ID_HORARIO, ID_SETOR, MATRICULA_PLANTONISTA) VALUES (GF_SEQ_ID_ALOCACAO.nextval, 4, 4, 12007);
INSERT INTO GF_ALOCACAO (ID_ALOCACAO, ID_HORARIO, ID_SETOR, MATRICULA_PLANTONISTA) VALUES (GF_SEQ_ID_ALOCACAO.nextval, 5, 5, 12008);
INSERT INTO GF_ALOCACAO (ID_ALOCACAO, ID_HORARIO, ID_SETOR, MATRICULA_PLANTONISTA) VALUES (GF_SEQ_ID_ALOCACAO.nextval, 6, 6, 12009);
INSERT INTO GF_ALOCACAO (ID_ALOCACAO, ID_HORARIO, ID_SETOR, MATRICULA_PLANTONISTA) VALUES (GF_SEQ_ID_ALOCACAO.nextval, 1, 3, 12010);
